package com.github.leftisttachyon.dsiworld.service;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * A series of tests that ensure the validity of {@link IdGeneratorServiceImpl} and my sanity
 *
 * @author Jed Wang
 * @since 1.0.0
 */
@SpringBootTest
public class IdGenerationTests {
    @Autowired
    private IdGeneratorServiceImpl idGenerator;

    /**
     * A test that ensures that all longs generated by the code is within a certain range.
     */
    @Test
    public void rangeTest() {
        for (int i = 0; i < 1_000; i++) {
            long l = idGenerator.getRandLong();
            String s = Long.toString(l, 36);

            Assertions.assertTrue(s.length() <= 12 && s.length() >= 3);
        }
    }

    @Value("${azure.blob.name}")
    private String blobName;
    @Value("${azure.blob.key}")
    private String blobKey;

    /**
     * A test to make sure that autowiring still exists
     */
    @Test
    public void blobNameTest() {
        System.out.println(blobName);
        Assertions.assertNotNull(blobName);

        System.out.println(blobKey);
        Assertions.assertNotNull(blobKey);
    }
}
